//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosSolicitud
    {
        public int idComentarioSolicitud { get; set; }
        public string comentario { get; set; }
        public string rutaAdjunto { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEnvioComentario { get; set; }
        public Nullable<bool> comentarioCliente { get; set; }
        public Nullable<bool> mensajesSinLeer { get; set; }
        public Nullable<int> idReserva { get; set; }
    }
}
