//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuestas
    {
        public Encuestas()
        {
            this.Preguntas = new HashSet<Preguntas>();
        }
    
        public int idEncuesta { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idTipoEncuesta { get; set; }
        public Nullable<bool> esActiva { get; set; }
    
        public virtual TiposEncuesta TiposEncuesta { get; set; }
        public virtual ICollection<Preguntas> Preguntas { get; set; }
    }
}
