//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestasAsignadas
    {
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
        public int idEncuestaAsignada { get; set; }
        public Nullable<int> idTipoEncuesta { get; set; }
    
        public virtual Negocio Negocio { get; set; }
        public virtual TiposEncuesta TiposEncuesta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
