//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        public Preguntas()
        {
            this.RtasXEncuestasAsignadas = new HashSet<RtasXEncuestasAsignadas>();
        }
    
        public int idPregunta { get; set; }
        public Nullable<int> idClasifPregunta { get; set; }
        public string textoPregunta { get; set; }
        public Nullable<int> idEncuesta { get; set; }
        public Nullable<int> idTipoRespuesta { get; set; }
    
        public virtual ClasifPregunta ClasifPregunta { get; set; }
        public virtual Encuestas Encuestas { get; set; }
        public virtual Preguntas Preguntas1 { get; set; }
        public virtual Preguntas Preguntas2 { get; set; }
        public virtual TiposRespuesta TiposRespuesta { get; set; }
        public virtual ICollection<RtasXEncuestasAsignadas> RtasXEncuestasAsignadas { get; set; }
    }
}
