//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionesOtorgadas
    {
        public int idPromocion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaOtorgamiento { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public string codigo { get; set; }
        public Nullable<int> utilizada { get; set; }
        public Nullable<int> idNegocio { get; set; }
    
        public virtual Promociones Promociones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
