//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasPosibles
    {
        public int idRtaPosible { get; set; }
        public string nombre { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<int> idTipoRespuesta { get; set; }
    
        public virtual TiposRespuesta TiposRespuesta { get; set; }
    }
}
