//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposEncuesta
    {
        public TiposEncuesta()
        {
            this.Encuestas = new HashSet<Encuestas>();
            this.EncuestasAsignadas = new HashSet<EncuestasAsignadas>();
        }
    
        public int idTipoEncuesta { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Encuestas> Encuestas { get; set; }
        public virtual ICollection<EncuestasAsignadas> EncuestasAsignadas { get; set; }
    }
}
