//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DAL;
using System.ComponentModel.DataAnnotations;

namespace BussinesEntities
{
    public partial class EncuestaEntityIndexUsuario
    {
        public int idEncuestaAsignada { get; set; }
        public string TIPO { get; set; }
        public string NEGOCIO { get; set; }
        public DateTime ASIGNADA { get; set; }
        public string RESPUESTA { get; set; } 
    }
}
