﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DAL;
using System.ComponentModel.DataAnnotations;

namespace BussinesEntities
{
    public partial class EncuestaEntityIndex
    {
        public int idEncuesta { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public string ESTADO { get; set; }
        public int RESPUESTAS { get; set; }
    }
}